<?php include ("include/header.php"); ?>

<div id="content">

<div class="row">
<h2>W2S Solutions Private Limited Website Terms of Use</h2>
<h3>Last updated on: September 02, 2013</h3>

<p>Acknowledgement and Acceptance of Terms of Use. These terms of use (the "Terms of Use") are an agreement between W2S Solutions Private Limited. Unless otherwise stated, the Terms of Use contain the legal terms and conditions that govern your use of any website or web page operated or provided by W2S Solutions (collectively, " W2S Solutions Websites") including. But not limited to, upcomingeventz.com. By accessing, viewing, downloading or otherwise using W2S Solutions Websites or any webpage or feature of W2S Solutions Websites you agree to be bound by the Terms of Use and any other policies or agreements made part of the Terms of Use by reference, including without limitation, the Privacy Policy (as defined below).</p>

<p>IF YOU DO NOT AGREE TO THESE TERMS OF USE, THEN YOU MUST DISCONTINUE ACCESSING AND/OR USING ALL W2S Solutions WEBSITES. </p>

<p>W2S Solutions may modify these Terms of Use at any time, without notice and in its sole discretion. Your continued use of W2S Solutions Websites after any modification to the Terms of Use will constitute your acknowledgement and acceptance of the Terms of Use as modified. Please consult the Terms of Use regularly.</p>

<p><b>Privacy</b>. You can view W2S Solutions privacy policy (the " <b>Privacy Policy </b>”) here<a href="http://www.w2ssolutions.com/privacy-policy" class="boldLink"> http://www.w2ssolutions.com/privacy-policy</a>, which is incorporated herein by reference. The Privacy Policy provides your rights and our responsibilities with regard to our use of your personal information. We will not use your information in any way inconsistent with the purposes and limitations provided in the Privacy Policy.</p>

<p><b>Modification</b>. W2S Solutions reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, any W2S Solutions Website or any part thereof, with or without notice. W2S Solutions shall not be liable to you or to any third-party for any modification, suspension or discontinuance of such service. W2S Solutions may establish general practices and limits concerning use of W2S Solutions Websites.</p>

<p><b>Access and Use</b>. Subject to these Terms of Use, you may use W2S Solutions Websites as a " <b>Visitor</b> " (which means you are just browsing a W2S Solutions Website) or a " <b>Registered Member</b> " (which means you have registered as a member of a W2S Solutions Website and agreed to be bound by the terms and conditions of any agreements applicable to your registration). We do not represent that content or materials presented on the W2S Solutions Websites are appropriate or available for use in other locations or jurisdictions. If you access W2S Solutions Websites from a jurisdiction other than India, you agree that you do so on your own initiative, and are responsible for compliance with local laws.</p>

<p>W2S Solutions <b>Intellectual Property</b>. All text, software (including source and object codes), data, information, visual, oral or other digital material, and all other content of any description available on W2S Solutions Websites or included in any services We offer (collectively, the " Content ”), and all worldwide copyrights, trademarks, service marks, patents, patent registration rights, trade secrets, know-how, database rights and all other rights in or relating to the Content are owned either by Us or third parties who have given Us permission to use it.</p>

<p><b>W2S Solutions Website Content</b>. We may provide an opportunity for users to exchange information, comments, ideas and opinions on W2S Solutions Websites. Information, ideas and opinions posted by users do not necessarily reflect the views of W2S Solutions. We do not assume responsibility or accept liability for the accuracy of any information, ideas and opinions posted by users. W2S Solutions shall not be liable regardless of the cause or duration, for any errors, inaccuracies, omissions or other defect in, the information contained within any W2S Solutions Website. We are not liable for any claims, damages or losses resulting from any information, ideas and opinions posted by users of a W2S Solutions Website. </p>

<p><b>Indemnification</b>. You agree to indemnify and hold against W2S Solutions, its officers, directors, employees, suppliers and licensors (collectively, the " <b>W2S Solutions Parties</b> ”) harmless from and against any and all liability, losses, costs, and expenses (including legal fees) incurred by any W2S Solutions Party in connection with any claim (whether by W2S Solutions and/or a third-party), including without limitation, claims for defamation, violation of rights of publicity and/or privacy, copyright infringement, or trademark infringement, that arises out of: (i) your connection to, access or use of any W2S Solutions Websites; (ii) your violation of these Terms of Use; or (iii) your violation of the rights of any other person or entity.</p>

<p>We reserve the right to assume the exclusive defense and control of any matter for which you are required to indemnify Us, and you agree to cooperate with our defense of these claims.</p>

<p><b>Disclaimer</b>. YOUR USE OF W2S Solutions WEBSITES IS AT YOUR SOLE RISK. W2S SOLUTIONS WEBSITES ARE PROVIDED "AS IS". THE W2S SOLUTIONS PARTIES DO NOT WARRANT THE ACCURACY, ADEQUACY, TIMELINESS, OR COMPLETENESS OF W2S SOLUTIONS WEBSITES OR ANY PART THEREOF, AND DISCLAIM LIABILITY FOR ANY ERRORS OR OMISSIONS. NO WARRANTY OR CONDITION OF ANY KIND (IMPLIED, EXPRESS, OR STATUTORY) IS GIVEN IN CONNECTION WITH W2S SOLUTIONS WEBSITES. </p>

<p>W2S SOLUTIONS DISCLAIMS ANY RESPONSIBILITY FOR THE DELETION, THE FAILURE TO STORE, THE MISDELIVERY, OR THE UNTIMELY DELIVERY OF ANY INFORMATION OR MATERIAL. WE DISCLAIM ANY RESPONSIBILITY FOR ANY HARM RESULTING FROM DOWNLOADING OR ACCESSING ANY INFORMATION OR MATERIAL ON THE INTERNET USING W2S SOLUTIONS WEBSITES.</p>

<p><b>Limitation Of Liability</b>. THE W2S SOLUTIONS PARTIES WILL NOT BE LIABLE FOR ANY DAMAGES, LOSSES OR EXPENSES (INCLUDING, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES) ARISING FROM THE USE OR INABILITY TO USE W2S SOLUTIONS WEBSITES OR W2S Solutions WEBSITES INFORMATION, OR AN ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY, COMPUTER VIRUS, SYSTEM FAILURE, LOSS OF DATA OR OTHERWISE, EVEN IF SUCH W2S SOLUTIONS PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, LOSSES OF EXPENSES. </p>

<p>Some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, thus the above limitations may not apply to you.</p>

<p><b>Third Party Websites and Links</b>. W2S Solutions Websites may contain links to or the content of/from third party websites (collectively, " <b>Third Party Websites</b> ”). Third Party Websites are not owned or controlled by W2S Solutions, therefore W2S Solutions has no control over any domain name, products, services, materials or other information in or available through Third Party Websites. We assume no responsibility for any Third Party Website including, but not limited to, any content within a Third Party Website. You agree that You assume all risk when accessing any Third Party Websites, and release W2S Solutions from any and all liability resulting from the access and/or use of Third Party Websites. Access to any Third Party Websites through W2S Solutions Websites, regardless of whether a Third Party Website is linked from any W2S Solutions Websites, is entirely at Your own risk and it is Your responsibility to take all protective measures to guard against viruses or other destructive devices, programs. W2S Solutions makes no representation or warranty regarding, nor endorses, any Third Party Websites or the information appearing thereon or therein or any of the products or services described thereon or therein.</p>

<p><b>Security</b>. W2S Solutions reserves the right to fully cooperate with any law enforcement authorities or court order requesting or directing W2S Solutions to disclose the identity of anyone posting any e-mail or other messages, or publishing or otherwise making available any other user-generated content that is believed or alleged (reasonably or not) to violate these Terms of Use or any law or regulation. YOU HEREBY WAIVE AND HOLD HARMLESS W2S SOLUTIONS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY W2S SOLUTIONS DURING OR AS A RESULT OF ANY INVESTIGATIONS AND/OR FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER W2S SOLUTIONS OR LAW ENFORCEMENT AUTHORITIES.</p>

<p><b>Submission of Ideas or Suggestions</b>. W2S Solutions is always improving the W2S Solutions Websites and the services and developing new features. If you have ideas or suggestions regarding improvements or additions, W2S Solutions would like to hear them, however any submission will be subject to the Terms of Use. Under no circumstances will any disclosure of any idea or suggestion or related material to W2S Solutions and/or its affiliates or licensors be subject to any obligation of confidentiality or expectation of compensation. By submitting the idea or suggestion or any related material to W2S Solutions and/or its affiliates or licensors, you are waiving any and all rights including, without limitation, moral rights, that you may have in the idea or suggestion or any related material and are representing and warranting to W2S Solutions and/or its affiliates or licensors that the idea or suggestion or any related material are wholly original with you, that no one else has any rights in the idea or suggestion or any related material and that W2S Solutions and/or its affiliates or licensors is free to implement the idea or suggestion and to use the related material if it so desires, as provided or as modified by W2S Solutions Solutions and/or its affiliates or licensors, without obtaining permission or license from any third-party. </p>

<p><b>Beneficiaries</b>. The W2S Solutions Parties are not parties, but intended third-party beneficiaries of the Terms of Use, with a right to enforce these Terms of Use directly against you.</p>

<p><b>Assignment</b>. You may not assign any rights or obligations under these Terms of Use and any purported assignment shall be ineffective. W2S Solutions may assign or delegate all rights and obligations under these Terms of Use without notice to you.</p>

<p><b>Governing Law</b>. These Terms of Use shall be governed by and construed and interpreted in accordance with the laws of the State of Tamil Nadu and the laws of Indian applicable therein. You hereby irrevocably at torn to the non-exclusive jurisdiction of the courts of the State of Tamil Nadu, India, without regard to the conflicts of laws principles.</p>

<p><b>General Provisions</b>. The failure of W2S Solutions to exercise or enforce any right or provision of the Terms of Use shall not operate as a waiver of such right or provision. The section titles in the Terms of Use are for convenience only and have no legal or contractual effect. If any provision of the Terms of Use is unlawful, void or unenforceable, that provision is deemed severable from the Terms of Use and does not affect the validity and enforceability of any remaining provisions.</p>

</div>
</div><!-- end #content -->
        
<?php include("include/footer.php"); ?>